# Set to true to add assignees to pull requests
addAssignees: true

# A list of assignees, overrides reviewers if set
assignees:
  - ${{github.actor}}

# A number of assignees to add to the pull request
# Set to 0 to add all of the assignees.
# Uses numberOfReviewers if unset.
numberOfAssignees: 1

# A list of labels to be added to pull requests
addLabels:
  - "feat 💡"
