services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/conf.d/${SERVER_NGINX_CONF}:/etc/nginx/conf.d/${SERVER_NGINX_CONF}
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - springboot

  springboot:
    container_name: springboot
    image: ${DOCKER_USERNAME}/bottles:${DOCKER_TAG}
    environment:
      - TZ=Asia/Seoul
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_BUCKET=${S3_BUCKET}
      - S3_REGION=${S3_REGION}
      - ACCESS_TOKEN_SECRET_KEY=${ACCESS_TOKEN_SECRET_KEY}
      - REFRESH_TOKEN_SECRET_KEY=${REFRESH_TOKEN_SECRET_KEY}
      - NAVER_SMS_SERVICE_ID=${NAVER_SMS_SERVICE_ID}
      - NAVER_SMS_API_KEY=${NAVER_SMS_API_KEY}
      - NAVER_SMS_SECRET_KEY=${NAVER_SMS_SECRET_KEY}
      - NAVER_SMS_SENDER_PHONE=${NAVER_SMS_SENDER_PHONE}
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    container_name: mysql
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER_NAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data/mysql/:/var/lib/mysql
      - ./db/mysql/config:/etc/mysql/conf.d
