services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/conf.d/${SERVER_NGINX_CONF}:/etc/nginx/conf.d/${SERVER_NGINX_CONF}
      - /etc/letsencrypt:/etc/letsencrypt

  springboot_blue:
    container_name: springboot_blue
    image: ${DOCKER_USERNAME}/bottles-api:${DOCKER_TAG}
    environment:
      TZ: Asia/Seoul
      DB_USER_NAME: ${DB_USER_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_BUCKET: ${S3_BUCKET}
      S3_REGION: ${S3_REGION}
      ACCESS_TOKEN_SECRET_KEY: ${ACCESS_TOKEN_SECRET_KEY}
      REFRESH_TOKEN_SECRET_KEY: ${REFRESH_TOKEN_SECRET_KEY}
      NAVER_SMS_SERVICE_ID: ${NAVER_SMS_SERVICE_ID}
      NAVER_SMS_API_KEY: ${NAVER_SMS_API_KEY}
      NAVER_SMS_SECRET_KEY: ${NAVER_SMS_SECRET_KEY}
      NAVER_SMS_SENDER_PHONE: ${NAVER_SMS_SENDER_PHONE}
      IS_MATCHING_ACTIVE: ${IS_MATCHING_ACTIVE}
      FCM_ADMIN_KEY_PATH: /app/config/bottles-firebase-adminsdk.json
      SUPER_USER_NUMBER: ${SUPER_USER_NUMBER}
      SUPER_USER_NUMBER_V2: ${SUPER_USER_NUMBER_V2}
      APPLE_KEY_ID: ${APPLE_KEY_ID}
      APPLE_KEY_ID_PATH: /api/config/apple-auth-key.p8
      APPLE_CLIENT_ID: ${APPLE_CLIENT_ID}
      APPLE_TEAM_ID: ${APPLE_TEAM_ID}
      LOGSTASH_HOST: ${LOGSTASH_HOST}
      LOGSTASH_PORT: ${LOGSTASH_PORT}
    ports:
      - "8080"
    volumes:
      - ${FCM_ADMIN_KEY_PATH}:/app/config/bottles-firebase-adminsdk.json
      - ${APPLE_KEY_ID_PATH}:/api/config/apple-auth-key.p8
    depends_on:
      - db

  springboot_green:
    container_name: springboot_green
    image: ${DOCKER_USERNAME}/bottles-api:${DOCKER_TAG}
    environment:
      TZ: Asia/Seoul
      DB_USER_NAME: ${DB_USER_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_BUCKET: ${S3_BUCKET}
      S3_REGION: ${S3_REGION}
      ACCESS_TOKEN_SECRET_KEY: ${ACCESS_TOKEN_SECRET_KEY}
      REFRESH_TOKEN_SECRET_KEY: ${REFRESH_TOKEN_SECRET_KEY}
      NAVER_SMS_SERVICE_ID: ${NAVER_SMS_SERVICE_ID}
      NAVER_SMS_API_KEY: ${NAVER_SMS_API_KEY}
      NAVER_SMS_SECRET_KEY: ${NAVER_SMS_SECRET_KEY}
      NAVER_SMS_SENDER_PHONE: ${NAVER_SMS_SENDER_PHONE}
      IS_MATCHING_ACTIVE: ${IS_MATCHING_ACTIVE}
      FCM_ADMIN_KEY_PATH: /app/config/bottles-firebase-adminsdk.json
      SUPER_USER_NUMBER: ${SUPER_USER_NUMBER}
      SUPER_USER_NUMBER_V2: ${SUPER_USER_NUMBER_V2}
      APPLE_KEY_ID: ${APPLE_KEY_ID}
      APPLE_KEY_ID_PATH: /api/config/apple-auth-key.p8
      APPLE_CLIENT_ID: ${APPLE_CLIENT_ID}
      APPLE_TEAM_ID: ${APPLE_TEAM_ID}
      LOGSTASH_HOST: ${LOGSTASH_HOST}
      LOGSTASH_PORT: ${LOGSTASH_PORT}
    ports:
      - "8080"
    volumes:
      - ${FCM_ADMIN_KEY_PATH}:/app/config/bottles-firebase-adminsdk.json
      - ${APPLE_KEY_ID_PATH}:/api/config/apple-auth-key.p8
    depends_on:
      - db

  db:
    container_name: mysql
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER_NAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data/mysql/:/var/lib/mysql
      - ./db/mysql/config:/etc/mysql/conf.d
