server:
  port: 8080

spring:
  profiles:
    active: local
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

---
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/bottles?useSSL=false
    username: root
    password: root

logging:
  level:
    org:
      springframework: INFO
