name: Bottles Deploy Workflow

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash

      - name: Build with gradle
        run: ./gradlew clean build
        shell: bash

      - name: Docker build & push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build --platform linux/amd64 -f Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/bottles .
          docker push ${{ secrets.DOCKER_USERNAME }}/bottles

      - name: Transfer docker-compose file use SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER_NAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          source: "./docker-compose.yml"
          target: "/docker"

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER_NAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          script: |
            export SERVER_NGINX_CONF=${{ secrets.SERVER_NGINX_CONF }}
            export DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
            export DB_DATABASE=${{ secrets.DB_DATABASE }}
            export DB_USER_NAME=${{ secrets.DB_USER_NAME }}
            export DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            
            sudo docker ps
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/bottles
            cd docker
            docker-compose up -d
            sudo docker image prune -f
